/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Nicolás
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        panelInicio.setVisible(true);
        panelMonitores.setVisible(false);
        panelSocios.setVisible(false);
        panelActividades.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMonitores = new javax.swing.JPanel();
        vistaInicioMonitores1 = new Vista.VistaInicioMonitores();
        panelSocios = new javax.swing.JPanel();
        vistaInicioSocios1 = new Vista.VistaInicioSocios();
        panelActividades = new javax.swing.JPanel();
        vistaInicioActividades1 = new Vista.VistaInicioActividades();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemInicio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemMonitores = new javax.swing.JMenuItem();
        jmenu3 = new javax.swing.JMenu();
        menuItemSocios = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemActividades = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pantalla de Inicio");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(661, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        panelMonitores.setLayout(new java.awt.BorderLayout());
        panelMonitores.add(vistaInicioMonitores1, java.awt.BorderLayout.CENTER);

        panelSocios.setLayout(new java.awt.BorderLayout());
        panelSocios.add(vistaInicioSocios1, java.awt.BorderLayout.CENTER);

        panelActividades.setLayout(new java.awt.BorderLayout());
        panelActividades.add(vistaInicioActividades1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelMonitores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelMonitores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");

        menuItemInicio.setText("Volver a la página principal");
        menuItemInicio.setActionCommand("MostrarInicio");
        menuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInicioActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInicio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Monitores");

        menuItemMonitores.setText("Gestión de Monitores");
        menuItemMonitores.setActionCommand("MostrarMonitores");
        jMenu2.add(menuItemMonitores);

        jMenuBar1.add(jMenu2);

        jmenu3.setText("Socios");

        menuItemSocios.setText("Gestión de Sacios");
        menuItemSocios.setActionCommand("MostrarSocios");
        jmenu3.add(menuItemSocios);

        jMenuBar1.add(jmenu3);

        jMenu4.setText("Actividades");

        menuItemActividades.setText("Gestión de Actividades");
        menuItemActividades.setActionCommand("MostrarActividades");
        jMenu4.add(menuItemActividades);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");

        menuItemSalir.setText("Salir de la aplicación");
        menuItemSalir.setActionCommand("SalirAplicacion");
        jMenu5.add(menuItemSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jmenu3;
    public javax.swing.JMenuItem menuItemActividades;
    public javax.swing.JMenuItem menuItemInicio;
    public javax.swing.JMenuItem menuItemMonitores;
    public javax.swing.JMenuItem menuItemSalir;
    public javax.swing.JMenuItem menuItemSocios;
    public javax.swing.JPanel panelActividades;
    private javax.swing.JPanel panelContenedor;
    public javax.swing.JPanel panelInicio;
    public javax.swing.JPanel panelMonitores;
    public javax.swing.JPanel panelSocios;
    private Vista.VistaInicioActividades vistaInicioActividades1;
    private Vista.VistaInicioMonitores vistaInicioMonitores1;
    private Vista.VistaInicioSocios vistaInicioSocios1;
    // End of variables declaration//GEN-END:variables
}
