/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Nicolás
 */
public class VistaMonitores extends javax.swing.JPanel {

    private Controlador.ControladorMonitor controladorMonitor;
    /**
     * Creates new form VistaInicioMonitores
     */
    public VistaMonitores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMonitores = new javax.swing.JTable();
        btnNuevoMonitor = new javax.swing.JButton();
        btnBajaMonitor = new javax.swing.JButton();
        btnActualizarMonitor = new javax.swing.JButton();

        jLabel1.setText("Gestión de Monitores");

        TablaMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaMonitores);

        btnNuevoMonitor.setText("Nuevo Monitor");
        btnNuevoMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoMonitorActionPerformed(evt);
            }
        });

        btnBajaMonitor.setText("Baja de Monitor");
        btnBajaMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaMonitorActionPerformed(evt);
            }
        });

        btnActualizarMonitor.setText("Actualización de Monitor");
        btnActualizarMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMonitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoMonitor)
                                .addGap(31, 31, 31)
                                .addComponent(btnBajaMonitor)
                                .addGap(34, 34, 34)
                                .addComponent(btnActualizarMonitor)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoMonitor)
                    .addComponent(btnBajaMonitor)
                    .addComponent(btnActualizarMonitor)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMonitorActionPerformed
        // TODO add your handling code here:
        if(controladorMonitor != null)
        {
            controladorMonitor.abrirVentanaNuevoMonitor();
        }
    }//GEN-LAST:event_btnNuevoMonitorActionPerformed

    private void btnBajaMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaMonitorActionPerformed
        // TODO add your handling code here:
        if(controladorMonitor != null)
        {
            controladorMonitor.bajaMonitor();
        }
    }//GEN-LAST:event_btnBajaMonitorActionPerformed

    private void btnActualizarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMonitorActionPerformed
        // TODO add your handling code here:
        if(controladorMonitor != null)
        {
            controladorMonitor.actualizarMonitor();
        }
    }//GEN-LAST:event_btnActualizarMonitorActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMonitores;
    private javax.swing.JButton btnActualizarMonitor;
    private javax.swing.JButton btnBajaMonitor;
    private javax.swing.JButton btnNuevoMonitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTablaMonitores() {
        return TablaMonitores;
    }
    
    public javax.swing.JButton getBtnNuevoMonitor() {
        return btnNuevoMonitor;
    }
    
    public javax.swing.JButton getBtnBajaMonitor() {
        return btnBajaMonitor;
    }
    
    public javax.swing.JButton getBtnActualizarMonitor() {
        return btnActualizarMonitor;
    }
    
    public void setControladorMonitor(Controlador.ControladorMonitor controladorMonitor)
    {
        this.controladorMonitor=controladorMonitor;
    }
}
